//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restful.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int Id { get; set; }
        public int Id_TaiKhoan { get; set; }
        public int Id_SanPham { get; set; }
        public double ThanhToan { get; set; }

        public TaiKhoan TaiKhoan { get; set; }
        public SanPham SanPham { get; set; }
    }
}
