//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restful.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int Id { get; set; }
        public string TenDangNhap { get; set; }
        public string Matkhau { get; set; }
        public string Ten { get; set; }
        public string SDT { get; set; }
        public string Diachi { get; set; }
    }
}
